channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - pyarrow
  - mypy
  - tqdm
  - jupyterlab
  - keras
  - matplotlib
  - pip:
    - thinc[jax,tensorflow]==8.0.0a1
